services:
  backend:
    container_name: customer-list-application-backend
    build:
      context: ./quarkus-customer-backend
      dockerfile: src/main/docker/Dockerfile.native
    ports:
      - "8080:8080"
    networks:
      - quarkus-network
    command: ["./application", "-Dquarkus.http.host=0.0.0.0"] 

  frontend:
    build:
      context: ./vue-customer-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - quarkus-network

networks:
  quarkus-network:
    driver: bridge
