### Health Check

GET http://localhost:8080/q/health

###

@PAGE=0
@SIZE=1

GET {{BACKEND_URL}}/customer?page={{PAGE}}&size={{SIZE}}
content-type: application/json

###

POST {{BACKEND_URL}}/customer
content-type: application/json

{
	"name": "Philip J Fry",
	"address": "Brooklyn New York",
	"email": "philip_j_fry@aol.com",
	"telephone": "06-8341-7625"
}
